// resources/js/components/AutopilotModal.jsx
import { useState } from "react";

// ─── الـ Tones اللي بيختار منها المستخدم ─────────────────────────────────
const TONES = [
  { value: "friendly",  label: "😊 Friendly & Casual" },
  { value: "formal",    label: "💼 Formal & Professional" },
  { value: "humorous",  label: "😄 Humorous & Light" },
  { value: "inspiring", label: "🔥 Inspiring & Motivational" },
];

// ─── Step 1: الـ Form ─────────────────────────────────────────────────────
function Step1Form({ form, updateForm, pages, error, onGenerate }) {
  return (
    <div className="ap-step ap-step-form">

      <div className="ap-grid-2">

        <div>
          <label className="ap-label">Business Name *</label>
          <input
            value={form.business}
            onChange={(e) => updateForm("business", e.target.value)}
            className="ap-input"
            placeholder="e.g. Al-Asala Restaurant"
          />
        </div>

        <div>
          <label className="ap-label">Industry / Sector *</label>
          <input
            value={form.industry}
            onChange={(e) => updateForm("industry", e.target.value)}
            className="ap-input"
            placeholder="e.g. Restaurants, Fashion"
          />
        </div>

        <div>
          <label className="ap-label">Target Audience *</label>
          <input
            value={form.audience}
            onChange={(e) => updateForm("audience", e.target.value)}
            className="ap-input"
            placeholder="e.g. Young adults 18-35"
          />
        </div>

        <div>
          <label className="ap-label">Content Goal *</label>
          <input
            value={form.goal}
            onChange={(e) => updateForm("goal", e.target.value)}
            className="ap-input"
            placeholder="e.g. Increase sales, grow followers"
          />
        </div>

        {/* Dropdown - في Vue كان v-for، في React بنستخدم .map() */}
        <div>
          <label className="ap-label">Page *</label>
          <select
            value={form.page}
            onChange={(e) => updateForm("page", e.target.value)}
            className="ap-input"
          >
            <option value="">Select a page</option>
            {pages.map((page) => (
              <option key={page} value={page}>{page}</option>
            ))}
          </select>
        </div>

        <div>
          <label className="ap-label">Posts per Week *</label>
          <select
            value={form.postsPerWeek}
            onChange={(e) => updateForm("postsPerWeek", e.target.value)}
            className="ap-input"
          >
            <option value="3">3 posts / week (12/month)</option>
            <option value="4">4 posts / week (16/month)</option>
            <option value="5">5 posts / week (20/month)</option>
            <option value="7">7 posts / week (28/month)</option>
          </select>
        </div>

      </div>

      {/* Tone Selector */}
      <div>
        <label className="ap-label">Content Style *</label>
        <div className="ap-tone-grid">
          {TONES.map((tone) => (
            <button
              key={tone.value}
              type="button"
              // في Vue كان: :class="{ active: form.tone === tone.value }"
              // في React: template literal عادي
              className={`ap-tone-btn ${form.tone === tone.value ? "active" : ""}`}
              onClick={() => updateForm("tone", tone.value)}
            >
              {tone.label}
            </button>
          ))}
        </div>
      </div>

      {/* Error - في Vue: v-if="error" — في React: && */}
      {error && <div className="ap-error">{error}</div>}

      <button className="ap-btn-generate" onClick={onGenerate}>
        ⚡ Generate Full Month Plan
      </button>

    </div>
  );
}

// ─── Step 2: Loading ──────────────────────────────────────────────────────
function Step2Loading({ progress, loadingMsg }) {
  return (
    <div className="ap-step ap-step-loading">
      <div className="ap-spinner">⏳</div>
      <p className="ap-loading-title">AI is generating your plan...</p>
      <p className="ap-loading-msg">{loadingMsg}</p>
      <div className="ap-progress-track">
        <div className="ap-progress-bar" style={{ width: `${progress}%` }}></div>
      </div>
    </div>
  );
}

// ─── Step 3: Preview ──────────────────────────────────────────────────────
function Step3Preview({ posts, page, onBack, onConfirm, confirming }) {
  return (
    <div className="ap-step ap-step-preview">
      <div className="ap-summary">
        ✅ Generated <strong>{posts.length}</strong> posts for page <strong>{page}</strong>
      </div>
      <div className="ap-posts-list">
        {posts.map((post, i) => (
          <div key={i} className="ap-post-card">
            <div className="ap-post-card-header">
              <span className="ap-type-badge">{post.post_type}</span>
              <span className="ap-post-date">{post.scheduled_at}</span>
            </div>
            <p className="ap-post-preview">{post.content}</p>
          </div>
        ))}
      </div>
      <div className="ap-preview-actions">
        <button className="ap-btn-back" onClick={onBack}>← Regenerate</button>
        <button className="ap-btn-confirm" onClick={onConfirm} disabled={confirming}>
          {confirming ? "Scheduling..." : "Schedule All Now"}
        </button>
      </div>
    </div>
  );
}

// ─── Step 4: Success ──────────────────────────────────────────────────────
function Step4Success({ successMsg, onClose }) {
  return (
    <div className="ap-step ap-step-success">
      <div className="ap-success-icon">✅</div>
      <p className="ap-success-title">{successMsg || "All posts scheduled!"}</p>
      <p className="ap-success-sub">All posts are now visible in the calendar below.</p>
      <button className="ap-btn-done" onClick={onClose}>Got it, view calendar</button>
    </div>
  );
}

// ─── الـ Component الرئيسي ────────────────────────────────────────────────
export default function AutopilotModal({ show, pages = [], csrf, locale = "en", routes, onClose, onScheduled }) {

  const [step, setStep] = useState(1);
  const [error, setError] = useState("");
  const [confirming, setConfirming] = useState(false);
  const [generatedPosts, setGeneratedPosts] = useState([]);
  const [progress, setProgress] = useState(0);
  const [loadingMsg, setLoadingMsg] = useState("Analyzing your business...");
  const [successMsg, setSuccessMsg] = useState("");

  const [form, setForm] = useState({
    business: "",
    industry: "",
    audience: "",
    goal: "",
    page: "",
    postsPerWeek: "5",
    tone: "friendly",
  });

  // بدل v-model — بنحدث حقل واحد بالـ form
  function updateForm(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }));
  }

  function handleClose() {
    onClose?.();
    setTimeout(() => {
      setStep(1);
      setError("");
      setGeneratedPosts([]);
      setProgress(0);
    }, 300);
  }

  // Progress bar مثل Vue بالضبط
  function startProgressBar() {
    setProgress(0);
    const messages = [
      "Analyzing your business...",
      "Writing educational content...",
      "Adding promotional posts...",
      "Arranging dates and times...",
      "Reviewing the final plan...",
    ];
    let msgIdx = 0;
    let currentProgress = 0;

    const interval = setInterval(() => {
      currentProgress = Math.min(currentProgress + (currentProgress < 80 ? 2 : 0.3), 92);
      setProgress(currentProgress);
      if (msgIdx < messages.length && currentProgress > msgIdx * 18) {
        setLoadingMsg(messages[msgIdx++]);
      }
    }, 300);

    return () => { clearInterval(interval); setProgress(100); };
  }

  async function generate() {
    const { business, industry, audience, goal, page } = form;
    if (!business || !industry || !audience || !goal || !page) {
      setError("Please fill in all required fields.");
      return;
    }
    setError("");
    setStep(2);

    const stopProgress = startProgressBar();

    try {
      const res = await fetch(routes?.generate ?? "/autopilot/generate", {
        method: "POST",
        credentials: "same-origin",
        headers: { "Content-Type": "application/json", "X-CSRF-TOKEN": csrf },
        body: JSON.stringify({
          business_name:  business,
          industry,
          audience,
          goal,
          page_name:      page,
          posts_per_week: parseInt(form.postsPerWeek),
          tone:           form.tone,
        }),
      });

      const data = await res.json();
      stopProgress();

      if (!res.ok || data.error) {
        setStep(1);
        setError(data.error ?? "Generation failed, please try again.");
        return;
      }

      setGeneratedPosts(data.posts);
      setStep(3);

    } catch {
      stopProgress();
      setStep(1);
      setError("A connection error occurred.");
    }
  }

  async function confirm() {
    setConfirming(true);
    try {
      const res = await fetch(routes?.confirm ?? "/autopilot/confirm", {
        method: "POST",
        credentials: "same-origin",
        headers: { "Content-Type": "application/json", "X-CSRF-TOKEN": csrf },
        body: JSON.stringify({ page_name: form.page, posts: generatedPosts }),
      });

      const data = await res.json();
      setSuccessMsg(data.message ?? "All posts scheduled!");
      setStep(4);
      onScheduled?.(generatedPosts);

    } catch {
      // نبقى على step 3
    } finally {
      setConfirming(false);
    }
  }

  // لو مش ظاهر ما نعرض شي — بدل v-if على الـ backdrop
  if (!show) return null;

  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <div className="ap-backdrop" onClick={(e) => e.target === e.currentTarget && handleClose()}>
      <div className="ap-modal" dir={dir}>

        {/* Header */}
        <div className="ap-header">
          <div className="ap-header-left">
            <span className="ap-robot">🤖</span>
            <div>
              <h3 className="ap-title">AI Content Autopilot</h3>
              <p className="ap-subtitle">Full monthly content plan in one click</p>
            </div>
          </div>
          <button className="ap-close-btn" onClick={handleClose}>✕</button>
        </div>

        {/* Body - بنعرض الـ step الصح */}
        <div className="ap-body">
          {step === 1 && (
            <Step1Form
              form={form}
              updateForm={updateForm}
              pages={pages}
              error={error}
              onGenerate={generate}
            />
          )}
          {step === 2 && (
            <Step2Loading progress={progress} loadingMsg={loadingMsg} />
          )}
          {step === 3 && (
            <Step3Preview
              posts={generatedPosts}
              page={form.page}
              onBack={() => setStep(1)}
              onConfirm={confirm}
              confirming={confirming}
            />
          )}
          {step === 4 && (
            <Step4Success successMsg={successMsg} onClose={handleClose} />
          )}
        </div>

      </div>
    </div>
  );
}

// resources/js/components/AutopilotModal.vue
<template>
  <!-- Backdrop -->
  <Teleport to="body">
    <div
      v-if="show"
      class="ap-backdrop"
      @click.self="close"
    >
      <div class="ap-modal" dir="ltr">

        <!-- ── Header ── -->
        <div class="ap-header">
          <div class="ap-header-left">
            <span class="ap-robot">🤖</span>
            <div>
              <h3 class="ap-title">AI Content Autopilot</h3>
              <p class="ap-subtitle">Full monthly content plan in one click</p>
            </div>
          </div>
          <button class="ap-close-btn" @click="close">
            <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>

        <!-- ── Body ── -->
        <div class="ap-body">

          <!-- Step 1 – Form -->
          <div v-if="step === 1" class="ap-step ap-step-form">

            <div class="ap-grid-2">
              <div>
                <label class="ap-label">Business Name *</label>
                <input v-model="form.business" class="ap-input" placeholder="e.g. Al-Asala Restaurant">
              </div>
              <div>
                <label class="ap-label">Industry / Sector *</label>
                <input v-model="form.industry" class="ap-input" placeholder="e.g. Restaurants, Fashion">
              </div>
              <div>
                <label class="ap-label">Target Audience *</label>
                <input v-model="form.audience" class="ap-input" placeholder="e.g. Young adults 18-35">
              </div>
              <div>
                <label class="ap-label">Content Goal *</label>
                <input v-model="form.goal" class="ap-input" placeholder="e.g. Increase sales, grow followers">
              </div>
              <div>
                <label class="ap-label">Page *</label>
                <select v-model="form.page" class="ap-input">
                  <option value="">Select a page</option>
                  <option v-for="page in pages" :key="page" :value="page">{{ page }}</option>
                </select>
              </div>
              <div>
                <label class="ap-label">Posts per Week *</label>
                <select v-model="form.postsPerWeek" class="ap-input">
                  <option value="3">3 posts / week (12/month)</option>
                  <option value="4">4 posts / week (16/month)</option>
                  <option value="5">5 posts / week (20/month)</option>
                  <option value="7">7 posts / week (28/month)</option>
                </select>
              </div>
            </div>

            <!-- Tone selector -->
            <div>
              <label class="ap-label">Content Style *</label>
              <div class="ap-tone-grid">
                <button
                  v-for="t in tones"
                  :key="t.value"
                  type="button"
                  class="ap-tone-btn"
                  :class="{ active: form.tone === t.value }"
                  @click="form.tone = t.value"
                >
                  {{ t.label }}
                </button>
              </div>
            </div>

            <!-- Error -->
            <div v-if="error" class="ap-error">{{ error }}</div>

            <!-- Generate button -->
            <button class="ap-btn-generate" @click="generate">
              <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z"/>
              </svg>
              Generate Full Month Plan
            </button>
          </div>

          <!-- Step 2 – Loading -->
          <div v-else-if="step === 2" class="ap-step ap-step-loading">
            <svg class="ap-spinner" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <circle cx="12" cy="12" r="10" stroke-dasharray="60" stroke-dashoffset="20" stroke-linecap="round"/>
            </svg>
            <p class="ap-loading-title">AI is generating your plan...</p>
            <p class="ap-loading-msg">{{ loadingMsg }}</p>
            <div class="ap-progress-track">
              <div class="ap-progress-bar" :style="{ width: progress + '%' }"></div>
            </div>
          </div>

          <!-- Step 3 – Preview -->
          <div v-else-if="step === 3" class="ap-step ap-step-preview">
            <div class="ap-summary">
              ✅ Generated <strong>{{ generatedPosts.length }}</strong> posts for page
              <strong>{{ form.page }}</strong> — review before scheduling.
            </div>

            <div class="ap-posts-list">
              <div
                v-for="(post, i) in generatedPosts"
                :key="i"
                class="ap-post-card"
              >
                <div class="ap-post-card-header">
                  <span class="ap-type-badge" :style="typeBadgeStyle(post.post_type)">
                    {{ typeEmoji(post.post_type) }} {{ post.post_type }}
                  </span>
                  <span class="ap-post-date">
                    {{ formatDate(post.scheduled_at) }}
                  </span>
                </div>
                <p class="ap-post-preview">{{ post.content }}</p>
              </div>
            </div>

            <div class="ap-preview-actions">
              <button class="ap-btn-back" @click="step = 1">← Regenerate</button>
              <button class="ap-btn-confirm" :disabled="confirming" @click="confirm">
                <svg v-if="!confirming" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/>
                </svg>
                <svg v-else class="ap-spinner-sm" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <circle cx="12" cy="12" r="10" stroke-dasharray="60" stroke-dashoffset="20" stroke-linecap="round"/>
                </svg>
                {{ confirming ? 'Scheduling...' : 'Schedule All Now' }}
              </button>
            </div>
          </div>

          <!-- Step 4 – Success -->
          <div v-else-if="step === 4" class="ap-step ap-step-success">
            <div class="ap-success-icon">
              <svg width="32" height="32" fill="none" stroke="#10b981" stroke-width="2" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/>
              </svg>
            </div>
            <p class="ap-success-title">{{ successMsg }}</p>
            <p class="ap-success-sub">All posts are now visible in the calendar below.</p>
            <button class="ap-btn-done" @click="close">Got it, view calendar</button>
          </div>

        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { ref, reactive } from 'vue'

// ── Props ──────────────────────────────────────────────────────────────────
const props = defineProps({
  /** v-model:show */
  show: {
    type: Boolean,
    default: false,
  },
  /** Array of page name strings passed from Blade */
  pages: {
    type: Array,
    default: () => [],
  },
  /** Laravel CSRF token */
  csrf: {
    type: String,
    required: true,
  },
  /** Route URLs (passed from Blade so we keep zero hardcoded URLs) */
  routes: {
    type: Object,
    default: () => ({
      generate: '/autopilot/generate',
      confirm:  '/autopilot/confirm',
    }),
  },
})

// ── Emits ──────────────────────────────────────────────────────────────────
const emit = defineEmits(['update:show', 'scheduled'])

// ── State ──────────────────────────────────────────────────────────────────
const step    = ref(1)
const error   = ref('')
const confirming   = ref(false)
const successMsg   = ref('Your plan has been scheduled! 🎉')
const loadingMsg   = ref('Analyzing your business and crafting the right content')
const progress     = ref(0)
const generatedPosts = ref([])

const form = reactive({
  business:    '',
  industry:    '',
  audience:    '',
  goal:        '',
  page:        '',
  postsPerWeek: '5',
  tone:        'friendly',
})

// ── Constants ──────────────────────────────────────────────────────────────
const tones = [
  { value: 'friendly',  label: '😊 Friendly & Casual' },
  { value: 'formal',    label: '💼 Formal & Professional' },
  { value: 'humorous',  label: '😄 Humorous & Light' },
  { value: 'inspiring', label: '🔥 Inspiring & Motivational' },
]

const typeColorMap = {
  educational:   '#8b5cf6',
  promotional:   '#f59e0b',
  entertainment: '#ec4899',
  engagement:    '#06b6d4',
}

const typeEmojiMap = {
  educational:   '📚',
  promotional:   '🛍️',
  entertainment: '🎉',
  engagement:    '💬',
}

// ── Helpers ────────────────────────────────────────────────────────────────
function typeEmoji(type) {
  return typeEmojiMap[type] ?? '📝'
}

function typeBadgeStyle(type) {
  const color = typeColorMap[type] ?? '#6b7280'
  return {
    background: color + '18',
    color,
  }
}

function formatDate(dt) {
  if (!dt) return ''
  const [date, time] = dt.split(' ')
  return `${date} ${time?.slice(0, 5) ?? ''}`
}

function startProgressBar() {
  progress.value = 0
  const messages = [
    'Analyzing your business...',
    'Writing educational content...',
    'Adding promotional posts...',
    'Arranging dates and times...',
    'Reviewing the final plan...',
  ]
  let msgIdx = 0
  const interval = setInterval(() => {
    progress.value = Math.min(
      progress.value + (progress.value < 80 ? 2 : 0.3),
      92
    )
    if (msgIdx < messages.length && progress.value > msgIdx * 18) {
      loadingMsg.value = messages[msgIdx++]
    }
  }, 300)
  return () => {
    clearInterval(interval)
    progress.value = 100
  }
}

// ── Actions ────────────────────────────────────────────────────────────────
function close() {
  emit('update:show', false)
  // small delay so user sees the close animation before reset
  setTimeout(reset, 300)
}

function reset() {
  step.value = 1
  error.value = ''
  generatedPosts.value = []
  progress.value = 0
}

async function generate() {
  const { business, industry, audience, goal, page } = form
  if (!business || !industry || !audience || !goal || !page) {
    error.value = 'Please fill in all required fields.'
    return
  }
  error.value = ''
  step.value  = 2

  const stopProgress = startProgressBar()

  try {
    const res = await fetch(props.routes.generate, {
      method: 'POST',
      credentials: 'same-origin',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-TOKEN': props.csrf,
      },
      body: JSON.stringify({
        business_name:  business,
        industry,
        audience,
        goal,
        page_name:      page,
        posts_per_week: parseInt(form.postsPerWeek),
        tone:           form.tone,
      }),
    })

    const data = await res.json()
    stopProgress()

    if (!res.ok || data.error) {
      step.value  = 1
      error.value = data.error ?? 'Generation failed, please try again.'
      return
    }

    generatedPosts.value = data.posts
    step.value = 3

  } catch {
    stopProgress()
    step.value  = 1
    error.value = 'A connection error occurred.'
  }
}

async function confirm() {
  confirming.value = true
  try {
    const res = await fetch(props.routes.confirm, {
      method: 'POST',
      credentials: 'same-origin',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-TOKEN': props.csrf,
      },
      body: JSON.stringify({
        page_name: form.page,
        posts:     generatedPosts.value,
      }),
    })

    const data = await res.json()
    successMsg.value = data.message ?? 'Your plan has been scheduled! 🎉'
    step.value = 4

    // Tell the parent page to refresh the calendar
    emit('scheduled', generatedPosts.value)

  } catch {
    // stay on step 3, let user retry
  } finally {
    confirming.value = false
  }
}
</script>

<style scoped>
/* ── Backdrop ── */
.ap-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, .6);
  backdrop-filter: blur(4px);
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
}

/* ── Modal shell ── */
.ap-modal {
  background: #fff;
  border-radius: 24px;
  box-shadow: 0 32px 80px rgba(0, 0, 0, .25);
  max-width: 560px;
  width: 100%;
  max-height: 90vh;
  display: flex;
  flex-direction: column;
  animation: ap-in .3s cubic-bezier(.34, 1.56, .64, 1);
  overflow: hidden;
}

@keyframes ap-in {
  from { opacity: 0; transform: scale(.92) translateY(16px); }
  to   { opacity: 1; transform: scale(1)   translateY(0); }
}

/* ── Header ── */
.ap-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 22px 28px;
  border-bottom: 1px solid #f3f4f6;
  flex-shrink: 0;
}
.ap-header-left { display: flex; align-items: center; gap: 10px; }
.ap-robot       { font-size: 22px; }
.ap-title       { font-family: 'Syne', sans-serif; font-size: 18px; font-weight: 800; color: #0f1117; margin: 0; }
.ap-subtitle    { font-size: 12px; color: #9ca3af; margin: 0; }
.ap-close-btn {
  color: #9ca3af;
  border: none;
  background: #f3f4f6;
  border-radius: 8px;
  width: 32px;
  height: 32px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.ap-close-btn:hover { background: #e5e7eb; }

/* ── Body / steps ── */
.ap-body { flex: 1; overflow-y: auto; }
.ap-step { padding: 24px 28px; }

/* ── Step 1 form ── */
.ap-step-form { display: flex; flex-direction: column; gap: 16px; }
.ap-grid-2    { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
@media (max-width: 480px) { .ap-grid-2 { grid-template-columns: 1fr; } }

.ap-label {
  display: block;
  font-size: 12px;
  font-weight: 700;
  color: #374151;
  margin-bottom: 5px;
  text-transform: uppercase;
  letter-spacing: .04em;
}
.ap-input {
  width: 100%;
  padding: 9px 12px;
  border: 1.5px solid #e5e7eb;
  border-radius: 10px;
  font-size: 13px;
  color: #111827;
  outline: none;
  background: #fff;
  box-sizing: border-box;
  transition: border-color .15s;
}
.ap-input:focus { border-color: #7c3aed; }

.ap-tone-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
}
.ap-tone-btn {
  padding: 10px 14px;
  border: 1.5px solid #e5e7eb;
  border-radius: 10px;
  font-size: 13px;
  font-weight: 600;
  color: #6b7280;
  cursor: pointer;
  background: #fff;
  transition: all .15s;
  text-align: center;
}
.ap-tone-btn:hover  { border-color: #7c3aed; color: #7c3aed; }
.ap-tone-btn.active { border-color: #7c3aed; background: #f5f3ff; color: #7c3aed; }

.ap-error {
  background: #fee2e2;
  color: #991b1b;
  padding: 12px 16px;
  border-radius: 10px;
  font-size: 13px;
  font-weight: 500;
}

.ap-btn-generate {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: linear-gradient(135deg, #7c3aed, #2563eb);
  color: #fff;
  font-weight: 700;
  font-size: 14px;
  padding: 14px;
  border-radius: 12px;
  border: none;
  cursor: pointer;
  transition: opacity .15s;
}
.ap-btn-generate:hover { opacity: .88; }

/* ── Step 2 loading ── */
.ap-step-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 48px 28px;
}
.ap-spinner {
  width: 48px;
  height: 48px;
  color: #7c3aed;
  animation: spin 1s linear infinite;
  margin-bottom: 16px;
}
@keyframes spin { to { transform: rotate(360deg); } }

.ap-loading-title { font-size: 16px; font-weight: 700; color: #111827; margin: 0 0 8px; }
.ap-loading-msg   { font-size: 13px; color: #9ca3af; margin: 0 0 20px; }
.ap-progress-track {
  width: 100%;
  background: #f3f4f6;
  border-radius: 99px;
  height: 6px;
  overflow: hidden;
}
.ap-progress-bar {
  height: 100%;
  background: linear-gradient(90deg, #7c3aed, #2563eb);
  border-radius: 99px;
  transition: width .3s;
}

/* ── Step 3 preview ── */
.ap-step-preview { display: flex; flex-direction: column; gap: 16px; }
.ap-summary {
  background: #f0fdf4;
  border: 1px solid #a7f3d0;
  border-radius: 12px;
  padding: 14px 18px;
  font-size: 13px;
  color: #065f46;
  font-weight: 600;
}
.ap-posts-list {
  max-height: 320px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.ap-post-card {
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  padding: 12px 14px;
}
.ap-post-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}
.ap-type-badge {
  font-size: 11px;
  font-weight: 700;
  padding: 3px 10px;
  border-radius: 99px;
  text-transform: capitalize;
}
.ap-post-date { font-size: 11px; color: #9ca3af; }
.ap-post-preview {
  font-size: 12px;
  color: #374151;
  line-height: 1.5;
  margin: 0;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.ap-preview-actions { display: flex; gap: 10px; }
.ap-btn-back {
  flex: 1;
  padding: 12px;
  border: 1.5px solid #e5e7eb;
  border-radius: 12px;
  font-size: 13px;
  font-weight: 600;
  color: #6b7280;
  cursor: pointer;
  background: #fff;
  transition: background .15s;
}
.ap-btn-back:hover { background: #f9fafb; }
.ap-btn-confirm {
  flex: 2;
  background: linear-gradient(135deg, #10b981, #059669);
  color: #fff;
  font-weight: 700;
  font-size: 14px;
  padding: 12px;
  border-radius: 12px;
  border: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  transition: opacity .15s;
}
.ap-btn-confirm:hover:not(:disabled) { opacity: .88; }
.ap-btn-confirm:disabled { opacity: .6; cursor: not-allowed; }

.ap-spinner-sm {
  width: 16px;
  height: 16px;
  animation: spin 1s linear infinite;
}

/* ── Step 4 success ── */
.ap-step-success {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 48px 28px;
}
.ap-success-icon {
  width: 64px;
  height: 64px;
  background: #d1fae5;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 16px;
}
.ap-success-title { font-size: 18px; font-weight: 800; color: #111827; margin: 0 0 8px; }
.ap-success-sub   { font-size: 13px; color: #9ca3af; margin: 0 0 24px; }
.ap-btn-done {
  background: #f3f4f6;
  color: #374151;
  font-weight: 700;
  font-size: 14px;
  padding: 12px 28px;
  border-radius: 12px;
  border: none;
  cursor: pointer;
  transition: background .15s;
}
.ap-btn-done:hover { background: #e5e7eb; }
</style>
